### PR TITLE
Documentation fixes as promised on bug report

### PR DESCRIPTION
**Pull request by bertvandepoel**

### CODE REVIEW

**Comment by clue** [comment]
The changes LGTM, much appreciated :+1: 

Sorry for being nitpicky, but may I ask you split this up into two separate PRs?

**Comment by bertvandepoel** [comment]
I presume that means I need to cherry pick each of those into a seperate branch because you can only PR from the master?

**Comment by clue** [comment]
Yeah, cherry-picking into 2 separate branches is the way to go :+1:

**Comment by bertvandepoel** [comment]
It took some time (server failure, data recovery is the best in these conditions) but you should have PRs from two seperate branches :smile:

**Comment by clue** [comment]
No worries, and thanks for taking the time :+1: 

See #41 and #42.

**Pull request closed without merging**
